export const GET_ERRORS = "GET_ERRORS";
export const REGISTER_USER = "REGISTER_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const SET_PROFILE = "SET_PROFILE";
export const POST_LOADING = "POST_LOADING";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const ADD_PAGE = "ADD_PAGE";
export const PAGE_LOADING = "PAGE_LOADING";
export const PAGES_LOADING = "PAGES_LOADING";
export const GET_PAGE = "GET_PAGE";
export const GET_PAGES = "GET_PAGES";
export const DELETE_PAGE = "DELETE_PAGE";
export const ADD_TO_POSTARRAY = "ADD_TO_POSTARRAY";
export const REMOVE_FROM_POSTARRAY = "REMOVE_FROM_POSTARRAY";
export const ADD_ALL_TO_POSTARRAY = "ADD_ALL_TO_POSTARRAY";
